# Generated by Django 4.1.7 on 2023-04-03 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "courseid",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(blank=True, max_length=75, null=True)),
                (
                    "instructorid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollmentid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enrolledclass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.courses"
                    ),
                ),
                (
                    "studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instructor_QRCodes",
            fields=[
                ("qrid", models.AutoField(primary_key=True, serialize=False)),
                ("classmeeting", models.IntegerField()),
                ("qrcode", models.ImageField(upload_to="course_qr_codes")),
                ("creation_time", models.DateTimeField()),
                (
                    "courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.courses"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Profiles",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("user_type", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Uploaded_QRCodes",
            fields=[
                ("uploadid", models.AutoField(primary_key=True, serialize=False)),
                ("upload_qr", models.ImageField(upload_to="uploaded_qr_codes")),
                ("upload_time", models.DateTimeField()),
                (
                    "classmeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.instructor_qrcodes",
                    ),
                ),
                (
                    "enrollmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendanceid", models.AutoField(primary_key=True, serialize=False)),
                ("attended", models.BooleanField(default=False)),
                (
                    "classmeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.instructor_qrcodes",
                    ),
                ),
                (
                    "enrollmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
            ],
        ),
    ]
