# Generated by Django 4.1.7 on 2023-04-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "courseid",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollmentid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enrolledclass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.courses"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instructor_QRCodes",
            fields=[
                ("qrid", models.AutoField(primary_key=True, serialize=False)),
                ("classmeeting", models.IntegerField()),
                ("qrcode", models.ImageField(upload_to="course_qr_codes")),
                ("creation_time", models.DateTimeField()),
                (
                    "courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.courses"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.IntegerField(
                        max_length=8, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=20, null=True)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                ("user_class", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Uploaded_QRCodes",
            fields=[
                ("uploadid", models.AutoField(primary_key=True, serialize=False)),
                ("upload_qr", models.ImageField(upload_to="uploaded_qr_codes")),
                ("upload_time", models.DateTimeField()),
                (
                    "classmeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.instructor_qrcodes",
                    ),
                ),
                (
                    "enrollmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="studentid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.AddField(
            model_name="courses",
            name="instructorid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendanceid", models.AutoField(primary_key=True, serialize=False)),
                ("attended", models.BooleanField(default=False)),
                (
                    "classmeeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.instructor_qrcodes",
                    ),
                ),
                (
                    "enrollmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
            ],
        ),
    ]
