# Generated by Django 4.1.7 on 2023-04-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_profiles_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profiles",
            name="email",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "This email has already been registered."},
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
