# Generated by Django 4.1.7 on 2023-04-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_profiles_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="classtime",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="recurrence",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="instructorid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user_profiles"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="studentid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user_profiles"
            ),
        ),
    ]
