# Generated by Django 4.1.7 on 2023-04-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_users_alter_courses_instructorid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User_Profiles",
        ),
    ]
