# Generated by Django 4.1.7 on 2023-04-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_courses_classtime_courses_recurrence_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="enrolledclass",
            new_name="courseid",
        ),
    ]
