# Generated by Django 4.1.7 on 2023-04-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_users_user_profiles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_profiles",
            old_name="userid",
            new_name="user_id",
        ),
    ]
