# Generated by Django 4.1.7 on 2023-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_enrolledclass_enrollment_courseid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor_qrcodes",
            name="classmeeting",
        ),
        migrations.RemoveField(
            model_name="instructor_qrcodes",
            name="creation_time",
        ),
        migrations.RemoveField(
            model_name="instructor_qrcodes",
            name="qrcode",
        ),
        migrations.RemoveField(
            model_name="uploaded_qrcodes",
            name="classmeeting",
        ),
        migrations.AddField(
            model_name="courses",
            name="enddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="startdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instructor_qrcodes",
            name="class_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="instructor_qrcodes",
            name="class_code_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="courseid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="uploaded_qrcodes",
            name="upload_qr",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="uploaded_qrcodes",
            name="upload_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
