# Generated by Django 4.1.7 on 2023-04-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_userid_user_profiles_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profiles",
            name="user_id",
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
