# Generated by Django 4.1.7 on 2023-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_instructor_qrcodes_classmeeting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor_qrcodes",
            name="classmeeting",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
