# Generated by Django 4.1.7 on 2023-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_instructor_qrcodes_classmeeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="classmeeting",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
